/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Orion-plg\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-note': '&#xe900;',
		'icon-copy': '&#xeaaa;',
		'icon-redirect': '&#xeaac;',
		'icon-trash': '&#xeaad;',
		'icon-plus-circle': '&#xeaae;',
		'icon-info': '&#xeaaf;',
		'icon-three-dots': '&#xeab0;',
		'icon-drag-drop': '&#xeab1;',
		'icon-comment': '&#xeab2;',
		'icon-star-active': '&#xeab3;',
		'icon-time_empty': '&#xeab4;',
		'icon-upload_file': '&#xeab8;',
		'icon-description': '&#xeab9;',
		'icon-certificate-check': '&#xeaba;',
		'icon-time': '&#xeac0;',
		'icon-timer': '&#xeac3;',
		'icon-list-box': '&#xeac7;',
		'icon-download_file': '&#xeacc;',
		'icon-check-list': '&#xeacd;',
		'icon-ordered-list': '&#xeace;',
		'icon-bullet-list': '&#xeacf;',
		'icon-underline': '&#xead0;',
		'icon-strike': '&#xead1;',
		'icon-italic': '&#xead2;',
		'icon-bold': '&#xead3;',
		'icon-status-pause': '&#xead8;',
		'icon-users': '&#xeadb;',
		'icon-access-pending': '&#xeadc;',
		'icon-access-request': '&#xeadd;',
		'icon-warning': '&#xeade;',
		'icon-remainder': '&#xeadf;',
		'icon-kanban': '&#xeae0;',
		'icon-ss-calendar': '&#xeae1;',
		'icon-unsupported-file': '&#xeae2;',
		'icon-archive-file': '&#xeae3;',
		'icon-doc-file': '&#xeae4;',
		'icon-image-file': '&#xeae5;',
		'icon-pdf-file': '&#xeae6;',
		'icon-xls-file': '&#xeae7;',
		'icon-remove-cross': '&#xeae8;',
		'icon-yet-to-launch': '&#xeaea;',
		'icon-ir-tools-only': '&#xeaeb;',
		'icon-failure-cross1': '&#xeaec;',
		'icon-ir-medium': '&#xeaee;',
		'icon-ir-plus': '&#xeaef;',
		'icon-ir-premium': '&#xeaf0;',
		'icon-ir-basic': '&#xeaf1;',
		'icon-success-tick1': '&#xeaf2;',
		'icon-wave': '&#xeafa;',
		'icon-euroland-icon': '&#xeb01;',
		'icon-euroland-icon-primary': '&#xeb02;',
		'icon-Chat_Circle': '&#xeb06;',
		'icon-Mail': '&#xeb07;',
		'icon-Phone': '&#xeb08;',
		'icon-Bell_Notification': '&#xeb09;',
		'icon-attachment': '&#xeb0d;',
		'icon-about-us': '&#xe901;',
		'icon-about-us-inactive': '&#xe902;',
		'icon-agent-board-icon': '&#xe904;',
		'icon-arrow-up': '&#xe907;',
		'icon-assigned-user': '&#xe909;',
		'icon-attachment-icon': '&#xe90b;',
		'icon-blue-bell': '&#xe90c;',
		'icon-calendar-date-picker': '&#xe90d;',
		'icon-calendar-blue': '&#xe90e;',
		'icon-calendar-blue-slash': '&#xe90f;',
		'icon-calendar': '&#xe910;',
		'icon-card-assign': '&#xe911;',
		'icon-card-icon': '&#xe912;',
		'icon-caret-circle-left': '&#xe913;',
		'icon-caret-circle-right': '&#xe914;',
		'icon-clock-counter-clock-wise': '&#xe916;',
		'icon-clock-icon': '&#xe917;',
		'icon-close-icon-white': '&#xe919;',
		'icon-close-icon': '&#xe91b;',
		'icon-comment-icon': '&#xe91d;',
		'icon-contact-us-banner': '&#xe920;',
		'icon-cross-mark-not-fill': '&#xe980;',
		'icon-cross-mark': '&#xe981;',
		'icon-description-icon': '&#xe983;',
		'icon-due-date-calendar': '&#xe985;',
		'icon-edit-box-icon': '&#xe987;',
		'icon-email-icon': '&#xe98e;',
		'icon-failure-cross': '&#xe98f;',
		'icon-filter-icon': '&#xe991;',
		'icon-filter-rounded': '&#xe992;',
		'icon-filter-funnel': '&#xe994;',
		'icon-financial-release': '&#xe995;',
		'icon-green-bell': '&#xe998;',
		'icon-grid-view': '&#xe999;',
		'icon-info-icon': '&#xe99a;',
		'icon-location-icon': '&#xe99c;',
		'icon-login-background': '&#xe99d;',
		'icon-login-banner': '&#xe99f;',
		'icon-no-notification-data': '&#xea1d;',
		'icon-open-eye': '&#xeaa5;',
		'icon-open-eye-slash': '&#xeaa6;',
		'icon-orange-bell': '&#xeaa9;',
		'icon-orion-logo': '&#xed8e;',
		'icon-pencil-simple-line': '&#xf075;',
		'icon-phone-icon': '&#xf076;',
		'icon-printer-icon': '&#xf077;',
		'icon-radio-checked': '&#xf079;',
		'icon-radio-uncheck': '&#xf07a;',
		'icon-search-white': '&#xf07b;',
		'icon-source-link': '&#xf07d;',
		'icon-success-tick': '&#xf07e;',
		'icon-success-tick-large': '&#xf080;',
		'icon-success-tick-white': '&#xf081;',
		'icon-switch-active': '&#xf082;',
		'icon-switch-inactive': '&#xf085;',
		'icon-total-orders': '&#xf08c;',
		'icon-total-tools': '&#xf08e;',
		'icon-upload-simple': '&#xf094;',
		'icon-upsell': '&#xf096;',
		'icon-upsell-icon': '&#xf097;',
		'icon-user-switch': '&#xf098;',
		'icon-user-request': '&#xf099;',
		'icon-user-request-approval-pending': '&#xf09a;',
		'icon-users1': '&#xf09b;',
		'icon-workspace-switch': '&#xf09d;',
		'icon-x-circle': '&#xf09e;',
		'icon-close': '&#xeb0e;',
		'icon-dots-horizontal-triple': '&#xeb0f;',
		'icon-chevron-thin-down': '&#xeb10;',
		'icon-chevron-thin-right': '&#xeb11;',
		'icon-calendar1': '&#xeb12;',
		'icon-switch': '&#xeb13;',
		'icon-profile': '&#xeb14;',
		'icon-up-arrow': '&#xeb15;',
		'icon-down-arrow': '&#xeb16;',
		'icon-sync': '&#xeaa4;',
		'icon-hour-glass': '&#xeb70;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
